### PR TITLE
use SARSOP_jll!

### PR DESCRIPTION
**Pull request by MaximeBouton**
hopefully end of the build issues on windows.

### CODE REVIEW

**Comment by MaximeBouton** [comment]
Should fix #36 
@zsunberg let me know if you want me to hold the merge. 
I bumped the version number to 0.5.0.

**Comment by MaximeBouton** [comment]
This version will NOT be compatible with julia 1.0 since it does not support artifacts.

**Comment by zsunberg** [comment]
I think we should merge this now!

**Comment by zsunberg** [comment]
oops, did not mean to close

**Comment by rejuvyesh** [comment]
We can support v1 via the old method if we want to. Would require a few version checks and some helper functions.

**Comment by MaximeBouton** [comment]
Right now if someone wants to use SARSOP in julia 1.0 it should install v0.4. 
If we make significant changes to the API at some point it might be worth having a build script with a version check.

**Comment by zsunberg** [comment]
I don't think it's necessary to support 1.0. There are much better things
to use our time on!

Zachary Sunberg
Assistant Professor
Ann and H. J. Smead Aerospace Engineering Sciences
University of Colorado Boulder
https://zachary.sunberg.net/

**Comment by mykelk** [comment]
True!

**Pull request merged**
